server.port=8080
spring.application.name=VoiceChatServer
# spring.web.resources.static-locations=classpath:/static/   # uncomment if you serve frontend from Spring

spring.datasource.url=jdbc:h2:file:./data/voicechatdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2
