server.port=8080
spring.application.name=VoiceChatServer

# Konfiguracja bazy danych H2 (Plikowa - zostawiamy, ?eby dane nie znika?y po restarcie, ale...)
spring.datasource.url=jdbc:h2:file:./data/voicechatdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ustawienia Hibernate - ZMIANA NA create-drop (tylko na jedno uruchomienie!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# KONFIGURACJA KONSOLI H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true